### ISSUE TITLE
ENOENT when running on windows

### ISSUE THREAD

**Issue by Pomax** [jlongster/electron-with-server-example#4]
after cloning, renaming to `lightroom-catalog-helper`, and running `npm install`, running `npm start` on Windows 10 x64 leads to the following error:
```
C:\Users\Pomax\Documents\Git\projects\lightroom-catalog-helper>npm start

> electron-with-server-example@1.0.0 start C:\Users\Pomax\Documents\Git\projects\lightroom-catalog-helper
> electron .


 checking 1
Service path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + id
requested connection to  myapp1 /tmp/app.myapp1
Connecting client on Unix Socket : /tmp/app.myapp1


######
error:  { Error: connect ENOENT \\.\pipe\tmp-app.myapp1
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'connect',
  address: '\\\\.\\pipe\\tmp-app.myapp1' }
found socket 1
connection closed myapp1 /tmp/app.myapp1 Infinity tries remaining of Infinity
Yuki exceeded connection rety amount of  or stopRetrying flag set.
```

(Yuki being the machine name for this particular Win10 installation)

**Comment by Pomax** [comment]
I don't actually know what to make of this error - the actual electron app and server window start up "just fine" from what I can tell, and the factorial/phone buttons work.

**Comment by jlongster** [comment]
Sorry for the delay, haven't been checking github!

This is from `findOpenSocket`: https://github.com/jlongster/electron-with-server-example/blob/master/find-open-socket.js. It works by trying to connect to an existing socket to "probe" it. If there's nothing running there, it knows it's free.

I fixed in Actual long ago, and just copied over the relevant fix here: https://github.com/jlongster/electron-with-server-example/commit/7afdab9354186d796d28ef6e38a7dbb5dc5aab8d

**Comment by Pomax** [comment]
nice, cheers
